#############################################################################
# List of Ontario (and some external) universities and their synonyms
#############################################################################
UNIVERSITIES = {
    # Ontario
    "algoma": ["algoma university"],
    "brock": ["brock university"],
    "carleton": ["carleton university", "cu"],
    "guelph": ["university of guelph", "uofg"],
    "lakehead": ["lakehead university"],
    "laurentian": ["laurentian university"],
    "mcmaster" : ["mcmaster university", "mac"],
    "nipissing": ["nipissing university"],
    "ocad": ["ontario college of art and design university"],
    "ontario tech": ["ontario tech university", "otu", "o tech"],
    "ottawa": ["university of ottawa", "uofo"],
    "queen's": ["queen's university", "qu"],
    "Royal Military College": ["rmc"],
    "toronto (st. george)": ["university of toronto", "university of toronto st george", "uoft", "utsg", "toronto", "toronto (utsg)", "uoftears"],
    "toronto (mississauga)": ["university of toronto missisauga", "utm", "uoft m", "toronto (utm)", "uoft mississauga", "uoft sauga"],
    "toronto (scarborough)": ["university of toronto scarborough", "utsc", "uoft sc", "toronto (utsc)", "uoft scarborough"],
    "toronto metropolitan": ["toronto metropolitan university", "tmu", "ryerson"], 
    "trent": ["trent university"], 
    "waterloo": ["university of waterloo", "uw", "loo"], 
    "western ontario": ["university of western ontario", "uwo", "western","ivey"], 
    "wilfrid laurier": ["wilfrid laurier university", "wlu"], 
    "windsor": ["university of windsor"], 
    "york": ["york university", "yu", "yorku", "schulich"],
    
    # Not Ontario
    "british columbia": ["university of british columbia", "ubc", "ubc okanagan", "ubc vancouver"],
    "mcgill": ["mcgill university", "mcg"],
    "calgary": ["university of calgary", "ucal"], 
    "montreal": ["university de montreal", "udem"], 
    "alberta": ["university of alberta", "uofa"],
    "dalhousie": ["dalhousie university", "dal"], 
    "simon fraser": ["simon fraser university", "sfu"]
}


#############################################################################
# List of common university programs, decisions are classified into these
#############################################################################
PROGRAMS = {
    "accounting",
    "accounting and financial management",
    "aerospace engineering",
    "architectural engineering",
    "architecture",
    "arts",
    "arts/business",
    "bba/finmath",
    "biochemistry",
    "biology",
    "biomedical engineering",
    "biomedical science",
    "business administration",
    "business technology managment",
    "chemical engineering",
    "civil engineering",
    "commerce",
    "communications",
    "computer engineering",
    "computer science",
    "computing and financial management",
    "cs/bba",
    "cs/math/stats",
    "dev degree",
    "economics",
    "education",
    "electrical engineering",
    "engineering science",
    "environmental engineering",
    "environmental science",
    "forestry",
    "game design",
    "geomatics",
    "global business and digital arts",
    "health science",
    "humanities",
    "industrial engineering",
    "kinesiology",
    "law",
    "life science",
    "management",
    "management engineering",
    "materials engineering",
    "math",
    "math/bba",
    "mechanical engineering",
    "mechatronics engineering",
    "medical radiation sciences",
    "medical science",
    "mineral engineering",
    "nanotechnology engineering",
    "nuclear engineering",
    "nursing",
    "oenology and viticulture",
    "pharmacy",
    "physical sciences",
    "physics",
    "planning",
    "political science",
    "political science/law",
    "psychology",
    "public administration",
    "public affairs",
    "public health",
    "social sciences",
    "software engineering",
    "sport management",
    "systems design engineering",
    "undeclared engineering",
}